from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

class Laptop(BaseModel):
    id: int
    CPU: str
    RAM: str
    Almacenamiento: str

laptop_list=[
    Laptop(id=0, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=1, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=2, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=3, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=4, CPU = "AMD",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=5, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=6, CPU = "AMD",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=7, CPU = "AMD",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=8, CPU = "Intel",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=9, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=10, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=11, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=12, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=13, CPU = "AMD",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=14, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=15, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=16, CPU = "AMD",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=17, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=18, CPU = "Intel",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=19, CPU = "AMD",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=20, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=21, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=22, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=23, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=24, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=25, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=26, CPU = "Intel",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=27, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=28, CPU = "AMD",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=29, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=30, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=31, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=32, CPU = "Intel",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=33, CPU = "Intel",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=34, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=35, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=36, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=37, CPU = "AMD",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=38, CPU = "Intel",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=39, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=40, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=41, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=42, CPU = "AMD",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=43, CPU = "AMD",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=44, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=45, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=46, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=47, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=48, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=49, CPU = "AMD",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=50, CPU = "AMD",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=51, CPU = "AMD",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=52, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=53, CPU = "AMD",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=54, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=55, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=56, CPU = "Intel",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=57, CPU = "Intel",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=58, CPU = "Intel",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=59, CPU = "Intel",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=60, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=61, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=62, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=63, CPU = "AMD",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=64, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=65, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=66, CPU = "AMD",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=67, CPU = "AMD",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=68, CPU = "AMD",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=69, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=70, CPU = "AMD",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=71, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=72, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=73, CPU = "AMD",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=74, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=75, CPU = "AMD",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=76, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=77, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=78, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=79, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=80, CPU = "AMD",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=81, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=82, CPU = "AMD",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=83, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=84, CPU = "AMD",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=85, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=86, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=87, CPU = "AMD",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=88, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=89, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=90, CPU = "AMD",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=91, CPU = "Intel",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=92, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=93, CPU = "Intel",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=94, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=95, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=96, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=97, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=98, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=99, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=100, CPU = "Intel",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=101, CPU = "AMD",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=102, CPU = "AMD",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=103, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=104, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=105, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=106, CPU = "AMD",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=107, CPU = "AMD",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=108, CPU = "Intel",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=109, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=110, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=111, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=112, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=113, CPU = "AMD",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=114, CPU = "AMD",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=115, CPU = "Intel",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=116, CPU = "AMD",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=117, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=118, CPU = "AMD",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=119, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=120, CPU = "AMD",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=121, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=122, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=123, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=124, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=125, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=126, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=127, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=128, CPU = "AMD",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=129, CPU = "Intel",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=130, CPU = "Intel",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=131, CPU = "AMD",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=132, CPU = "AMD",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=133, CPU = "AMD",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=134, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=135, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=136, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=137, CPU = "Intel",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=138, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=139, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=140, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=141, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=142, CPU = "AMD",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=143, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=144, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=145, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=146, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=147, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=148, CPU = "AMD",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=149, CPU = "AMD",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=150, CPU = "Intel",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=151, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=152, CPU = "AMD",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=153, CPU = "AMD",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=154, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=155, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=156, CPU = "AMD",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=157, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=158, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=159, CPU = "Intel",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=160, CPU = "AMD",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=161, CPU = "Intel",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=162, CPU = "Intel",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=163, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=164, CPU = "Intel",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=165, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=166, CPU = "Intel",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=167, CPU = "AMD",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=168, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=169, CPU = "Intel",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=170, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=171, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=172, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=173, CPU = "AMD",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=174, CPU = "AMD",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=175, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=176, CPU = "Intel",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=177, CPU = "Intel",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=178, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=179, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=180, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=181, CPU = "AMD",RAM = "16GB",Almacenamiento = "512GB" ),
    Laptop(id=182, CPU = "Intel",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=183, CPU = "Intel",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=184, CPU = "AMD",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=185, CPU = "AMD",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=186, CPU = "Intel",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=187, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "256GB" ),
    Laptop(id=188, CPU = "AMD",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=189, CPU = "Intel",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=190, CPU = "AMD",RAM = "8GB",Almacenamiento = "1TB" ),
    Laptop(id=191, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=192, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=193, CPU = "Intel",RAM = "16GB",Almacenamiento = "1TB" ),
    Laptop(id=194, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "1TB" ),
    Laptop(id=195, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=196, CPU = "Apple_M1",RAM = "32GB",Almacenamiento = "512GB" ),
    Laptop(id=197, CPU = "AMD",RAM = "16GB",Almacenamiento = "256GB" ),
    Laptop(id=198, CPU = "Intel",RAM = "32GB",Almacenamiento = "256GB" ),
    Laptop(id=199, CPU = "Apple_M1",RAM = "8GB",Almacenamiento = "512GB" ),
    Laptop(id=200, CPU = "Apple_M1",RAM = "16GB",Almacenamiento = "256GB" )]


@app.get("/")
async def imprimir():
    return laptop_list


@app.get("/laptopclass/{id}")
async def laptopclass(id:int):
    laptops = filter (lambda laptop: laptop.id == id, laptop_list)
    try:
        return list(laptops)[0]
    except:
        return{"error":"No se ha encontrado la laptop que buscas"}